version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_minfulmedia
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - db
    ports:
      - "9000:9000"  # Tambahkan port untuk PHP-FPM

  webserver:
    image: nginx:alpine
    container_name: nginx_minfulmedia
    restart: unless-stopped
    ports:
      - "8000:80"  # Expose port 80 dari Nginx ke 8000 di host
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Pastikan path benar
    networks:
      - laravel
    depends_on:
      - app

  node:  # Tambahkan service Node.js
    image: node:16
    container_name: node_minfulmedia
    working_dir: /var/www
    volumes:
      - .:/var/www
    stdin_open: true
    tty: true
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_minfulmedia
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: minful
      MYSQL_DATABASE: minful
      MYSQL_PASSWORD: minful
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3307:3306"  # Perbaiki port MySQL: gunakan 3306 untuk container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
